version: '3.9'
services:
  loki:
    image: grafana/loki:2.4.2
    container_name: loki
    ports:
      - 3100:3100
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki
  promtail: 
    image: grafana/promtail:2.4.2
    container_name: promtail
    command: -config.file=/etc/promtail/config.yml
    volumes:
      - /var/log:/var/log
    networks:
      - loki
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - 3000:3000
    networks:
      - loki

networks:
  loki: